# lean

spacing = 2
padding = 2
hide_ascii = false
separator = ""
key_color = "Magenta"
separator_color = "White"

[palette]
visible = false

[bar]
glyph = "ߋ"
symbol_open = '['
symbol_close = ']'
hide_delimiters = true
visible = true

[box]
border = "rounded"
visible = false

[custom_ascii]
color = "DarkGray"
path = "~/ascii/becca"

[box.inner_margin]
x = 1
y = 0

[keys]
host = ""
distro = "󰌽"
de = ""
terminal = ""
packages = ""
shell = ""
cpu = ""
